### ISSUE TITLE
Requires /vendor directory to be present?

### ISSUE THREAD

**Issue by taupecat** [boxuk/wp-muplugin-loader#16]
Unless I'm missing something obvious, this package _requires_ the `/vendor` directory to be present on the filesystem in order to work. At least in my workflow, I don't commit the `/vendor` directory to the repository, but rather commit what's generated by `composer install` as far as core, plugins, themes, and must-use plugins go, and only transfer _that_ to the webserver.

Is there a way to get this loader to work _without_ having to also transfer any part of the `/vendor` directory to the webserver, i.e. to make it self-contained in the `[DOCROOT]/wp-contents/mu-plugins` directory?

**Comment by jenkoian** [comment]
Hi @taupecat 👋 it shouldn't require the vendor directory? 

It's a composer plugin, so will run during the `composer install`, which then should generate the loader file, you can either commit the generated loader file or have composer generate it during deployment (assuming you run composer during deployment). Does that answer your question? 

If it helps, our WP skeleton uses it which we've based a number of projects from, so might be a good example of usage: https://github.com/boxuk/wp-project-skeleton

**Comment by taupecat** [comment]
> Hi @taupecat 👋 it shouldn't require the vendor directory?

Um, well, since no other WordPress-related composer package I can think of (core, themes, and plugins) requires the vendor on the web server itself, I wouldn't have expected this to require it either.

I'll check out your skeleton, but I guess I'll also continue my search for a more fully-automated solution that doesn't require committing the vendor directory into revision control or transferring the whole or part of the vendor directory to the server. 🤷‍♀️

Thanks for the reply.

**Comment by jenkoian** [comment]
I think I understand now. Yes, the generated file to load `mu-plugin` directories does indeed use files from the vendor directory. This is expected and normal with most composer based projects, but I completely understand that WordPress plugins and themes can be installed using composer without a vendor directory being required. 

If you're looking for one that doesn't load from the vendor directory, perhaps this? https://github.com/wemakecustom/wp-mu-loader
